"""
Seed data for Equipment module - 18 products from the original frontend.
"""

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from backend.modules.equipment.models import Product


SEED_PRODUCTS = [
    {
        "name": "Mini Trator 25HP 4x4",
        "slug": "mini-trator-25hp-4x4",
        "price": 18900,
        "original_price": 24500,
        "category": "tratores",
        "description": "Ideal para pequenas propriedades. Motor diesel 25HP com tração nas 4 rodas, perfeito para cultivo, transporte e implementos leves.",
        "specs": {"Potência": "25 HP", "Tração": "4x4", "Peso": "890 kg", "Combustível": "Diesel", "Garantia": "2 anos", "Origem": "China"},
        "rating": 4.7,
        "reviews_count": 48,
        "stock": 12,
        "images": ["/products/trator-25hp.jpg"],
        "badge": "Mais Vendido",
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Motocultivador 10HP",
        "slug": "motocultivador-10hp",
        "price": 4800,
        "original_price": 5900,
        "category": "tratores",
        "description": "Motocultivador a diesel com enxada rotativa, ideal para hortas e canteiros. Compacto e de fácil operação.",
        "specs": {"Potência": "10 HP", "Largura Trabalho": "80 cm", "Peso": "135 kg", "Combustível": "Diesel", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.5,
        "reviews_count": 31,
        "stock": 20,
        "images": ["/products/motocultivador.jpg"],
        "badge": None,
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Microtrator 15HP Diesel",
        "slug": "microtrator-15hp-diesel",
        "price": 11200,
        "original_price": 13800,
        "category": "tratores",
        "description": "Microtrator versátil com 15HP, ótimo para pomares, vinícolas e áreas de difícil acesso.",
        "specs": {"Potência": "15 HP", "Tração": "4x2", "Peso": "580 kg", "Combustível": "Diesel", "Garantia": "2 anos", "Origem": "China"},
        "rating": 4.6,
        "reviews_count": 22,
        "stock": 8,
        "images": ["/products/microtrator-15hp.jpg"],
        "badge": "Novo",
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Arado Reversível 3 Discos",
        "slug": "arado-reversivel-3-discos",
        "price": 3200,
        "original_price": 3800,
        "category": "implementos",
        "description": "Arado reversível com 3 discos de 22 polegadas, para preparo de solo em pequenas e médias propriedades.",
        "specs": {"Discos": "3x 22\"", "Largura": "90 cm", "Peso": "180 kg", "Acoplamento": "3 pontos", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.3,
        "reviews_count": 15,
        "stock": 14,
        "images": ["/products/arado.jpg"],
        "badge": None,
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Roçadeira Hidráulica 1.5m",
        "slug": "rocadeira-hidraulica-1-5m",
        "price": 2800,
        "original_price": None,
        "category": "implementos",
        "description": "Roçadeira hidráulica com largura de corte de 1.5m para limpeza de pastagens e entrelinhas.",
        "specs": {"Largura Corte": "1.5 m", "Acionamento": "Hidráulico", "Peso": "220 kg", "Lâminas": "3", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.4,
        "reviews_count": 19,
        "stock": 10,
        "images": ["/products/rocadeira.jpg"],
        "badge": None,
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Grade Niveladora 20 Discos",
        "slug": "grade-niveladora-20-discos",
        "price": 4500,
        "original_price": 5200,
        "category": "implementos",
        "description": "Grade niveladora com 20 discos recortados para nivelamento e incorporação de restos culturais.",
        "specs": {"Discos": "20x 18\"", "Largura": "2.0 m", "Peso": "350 kg", "Acoplamento": "3 pontos", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.5,
        "reviews_count": 12,
        "stock": 6,
        "images": ["/products/grade.jpg"],
        "badge": None,
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Plantadeira Manual 2 Linhas",
        "slug": "plantadeira-manual-2-linhas",
        "price": 890,
        "original_price": None,
        "category": "implementos",
        "description": "Plantadeira manual de precisão para 2 linhas com disco de sementes intercambiável.",
        "specs": {"Linhas": "2", "Espaçamento": "Regulável", "Peso": "15 kg", "Material": "Aço inox", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.2,
        "reviews_count": 37,
        "stock": 50,
        "images": ["/products/plantadeira.jpg"],
        "badge": None,
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Drone Pulverizador 20L",
        "slug": "drone-pulverizador-20l",
        "price": 12400,
        "original_price": 15800,
        "category": "drones",
        "description": "Drone agrícola com tanque de 20L para pulverização de precisão. GPS integrado com planejamento de rota automático.",
        "specs": {"Capacidade": "20 L", "Autonomia": "15 min", "Vazão": "4 L/min", "GPS": "RTK", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.8,
        "reviews_count": 56,
        "stock": 5,
        "images": ["/products/drone-pulverizador.jpg"],
        "badge": "Destaque",
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Drone Mapeamento NDVI",
        "slug": "drone-mapeamento-ndvi",
        "price": 8900,
        "original_price": 10500,
        "category": "drones",
        "description": "Drone com câmera multiespectral para mapeamento NDVI e análise de saúde da vegetação.",
        "specs": {"Câmera": "Multiespectral 5 bandas", "Autonomia": "40 min", "Área/voo": "100 ha", "GPS": "RTK", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.7,
        "reviews_count": 28,
        "stock": 7,
        "images": ["/products/drone-ndvi.jpg"],
        "badge": None,
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Kit Filtros Diesel Universal",
        "slug": "kit-filtros-diesel-universal",
        "price": 280,
        "original_price": None,
        "category": "acessorios",
        "description": "Kit com 3 filtros de combustível, óleo e ar para motores diesel de até 30HP.",
        "specs": {"Itens": "3 filtros", "Compatibilidade": "Diesel até 30HP", "Garantia": "6 meses", "Origem": "China"},
        "rating": 4.1,
        "reviews_count": 63,
        "stock": 100,
        "images": ["/products/filtros.jpg"],
        "badge": None,
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Bateria Drone Agrícola 16000mAh",
        "slug": "bateria-drone-agricola-16000mah",
        "price": 1200,
        "original_price": 1500,
        "category": "acessorios",
        "description": "Bateria LiPo 6S 16000mAh para drones agrícolas de pulverização.",
        "specs": {"Capacidade": "16000 mAh", "Voltagem": "22.2V (6S)", "Peso": "1.8 kg", "Ciclos": "500+", "Garantia": "6 meses", "Origem": "China"},
        "rating": 4.4,
        "reviews_count": 41,
        "stock": 30,
        "images": ["/products/bateria.jpg"],
        "badge": None,
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Jogo Lâminas Roçadeira (6un)",
        "slug": "jogo-laminas-rocadeira-6un",
        "price": 180,
        "original_price": None,
        "category": "acessorios",
        "description": "Conjunto com 6 lâminas de reposição em aço temperado para roçadeiras hidráulicas.",
        "specs": {"Quantidade": "6 unidades", "Material": "Aço temperado", "Compatibilidade": "Universal", "Garantia": "3 meses", "Origem": "China"},
        "rating": 4.3,
        "reviews_count": 27,
        "stock": 80,
        "images": ["/products/laminas.jpg"],
        "badge": None,
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Correia Transmissão Implementos",
        "slug": "correia-transmissao-implementos",
        "price": 95,
        "original_price": None,
        "category": "acessorios",
        "description": "Correia em V para transmissão de implementos agrícolas. Alta durabilidade.",
        "specs": {"Tipo": "Correia V", "Material": "Borracha reforçada", "Compatibilidade": "Universal", "Garantia": "6 meses", "Origem": "China"},
        "rating": 4.0,
        "reviews_count": 18,
        "stock": 150,
        "images": ["/products/correia.jpg"],
        "badge": None,
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Sensor de Solo IoT",
        "slug": "sensor-solo-iot",
        "price": 790,
        "original_price": 950,
        "category": "tecnologia",
        "description": "Sensor IoT para monitoramento de umidade, pH e temperatura do solo em tempo real via WiFi.",
        "specs": {"Sensores": "Umidade, pH, Temperatura", "Conectividade": "WiFi/LoRa", "Bateria": "Solar + Li-ion", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.6,
        "reviews_count": 34,
        "stock": 25,
        "images": ["/products/sensor-solo.jpg"],
        "badge": "Novo",
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Estação Meteorológica Agrícola",
        "slug": "estacao-meteorologica-agricola",
        "price": 2400,
        "original_price": 2900,
        "category": "tecnologia",
        "description": "Estação meteorológica completa com sensores de temperatura, umidade, vento, chuva e radiação solar.",
        "specs": {"Sensores": "Temp, Umidade, Vento, Chuva, UV", "Display": "LCD colorido", "Conectividade": "WiFi", "Garantia": "2 anos", "Origem": "China"},
        "rating": 4.8,
        "reviews_count": 21,
        "stock": 10,
        "images": ["/products/estacao-meteo.jpg"],
        "badge": None,
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "GPS Agrícola RTK",
        "slug": "gps-agricola-rtk",
        "price": 3200,
        "original_price": 4100,
        "category": "tecnologia",
        "description": "Receptor GPS RTK com precisão centimétrica para piloto automático e mapeamento de lavouras.",
        "specs": {"Precisão": "2.5 cm RTK", "Canais": "184", "Conectividade": "Bluetooth + Serial", "Garantia": "2 anos", "Origem": "China"},
        "rating": 4.7,
        "reviews_count": 16,
        "stock": 8,
        "images": ["/products/gps-rtk.jpg"],
        "badge": None,
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Bomba Irrigação 2\" Diesel",
        "slug": "bomba-irrigacao-2-diesel",
        "price": 1600,
        "original_price": 1900,
        "category": "irrigacao",
        "description": "Bomba d'água diesel 2 polegadas com motor de alta pressão para irrigação e transferência.",
        "specs": {"Vazão": "30 m³/h", "Altura Manométrica": "26 m", "Motor": "6.5 HP Diesel", "Garantia": "1 ano", "Origem": "China"},
        "rating": 4.4,
        "reviews_count": 25,
        "stock": 15,
        "images": ["/products/bomba.jpg"],
        "badge": None,
        "free_shipping": False,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
    {
        "name": "Kit Irrigação Gotejamento 1ha",
        "slug": "kit-irrigacao-gotejamento-1ha",
        "price": 2200,
        "original_price": 2800,
        "category": "irrigacao",
        "description": "Kit completo de irrigação por gotejamento para 1 hectare com mangueira, conectores e filtro.",
        "specs": {"Área": "1 hectare", "Mangueira": "2000 m", "Gotejadores": "Autocompensantes", "Filtro": "Disco 120 mesh", "Garantia": "2 anos", "Origem": "China"},
        "rating": 4.5,
        "reviews_count": 33,
        "stock": 12,
        "images": ["/products/gotejamento.jpg"],
        "badge": "Mais Vendido",
        "free_shipping": True,
        "seller": "AgriTech Importadora",
        "origin": "China",
    },
]


async def seed_products(db: AsyncSession):
    """Seed products if table is empty."""
    count_result = await db.execute(select(func.count(Product.id)))
    count = count_result.scalar() or 0
    if count > 0:
        return 0

    for product_data in SEED_PRODUCTS:
        product = Product(**product_data)
        db.add(product)

    await db.flush()
    return len(SEED_PRODUCTS)
